4ilet/Find_Toilet

DockerFile

---
title: [BE-장엽] feat: dockerfile 생성
---
- 21
<br>
<br>
- DockerFile 생성
-
<br>
-
-

#21 [BE-장엽] feat: dockerfile 생성

---

README.md
backend/Dockerfile

---
title: "[BE] feat : 포트 변경 "
---
- 21 
<br>
<br>
- 포트 8080 -> 82
-
<br>
-
-

[BE] feat : 포트 변경

---

backend/src/main/resources/application.properties

---
title: [BE-윤주] feat: application.properties 추가
---
```
```
<br>
- closes #21
<br>
<br>
- springboot 프로젝트가 실행될 수 있도록 application.properties 에 DB 연동 정보를 추가했습니다.
<br>
-
-

[BE-윤주] feat: application.properties 추가

---

backend/Dockerfile
backend/build.gradle

---
title: [BE-윤주] feat: plain.jar 방지
---
```
```
<br>
- closes #21
<br>
<br>
- SNAPSHOT과 SANPSHOT-PLAIN, 2개의 jar이 생성됩니다. 이 중 SNAPSHOT-PLAIN의 생성을 방지하여 배포를 테스트합니다!
-
<br>
-
-

[BE-윤주] feat: plain.jar 방지

---

backend/build.gradle
backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/MemberEntity.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/domain/Member.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/MemberSaveRequestDto.java
backend/src/main/resources/application.properties
backend/src/main/resources/application.yml

---
title: "[FE/BE] feat : jpa 설정, 프로젝트 폴더구조 변경"
---
- #38
<br>
<br>
- jpa 설정
- application.properties -> application.yml 로 변경
- 폴더구조 변경
<br>

[BE-장엽] feat: jpa 설정, 프로젝트 폴더구조 변경

---

frontend/android/app/src/main/AndroidManifest.xml
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/intro_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/map_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/screens/select_theme_screen.dart
frontend/lib/utilities/global_func.dart
frontend/lib/utilities/icon_image.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/button.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/scroll_view.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/text_widget.dart
frontend/linux/flutter/generated_plugin_registrant.cc
frontend/linux/flutter/generated_plugins.cmake
frontend/macos/Flutter/GeneratedPluginRegistrant.swift
frontend/pubspec.lock
frontend/pubspec.yaml
frontend/windows/flutter/generated_plugin_registrant.cc
frontend/windows/flutter/generated_plugins.cmake

---
---
```
```
<br>
- closes #8 #10 #14 
<br>
<br>
- 검색 결과
- 지도 출력
- 검색창, 메인 화면 이동 버튼, 설정 화면 이동 버튼, 검색 버튼, 즐겨찾기 화면 이동 버튼
- 필터 선택 여부 확인
- 하단 시트 높이 변경, 스크롤
- 화장실 정보 출력
- 리뷰 작성 화면 이동 버튼
- 즐겨찾기 추가 버튼
- 길찾기 앱 이동 버튼
- 리뷰 작성
- 리뷰 입력 시, 키보드로 인해 화면 변경
- 별 터치 시 별점에 따른 별 색깔 변화
- 화장실명, 별점, 리뷰 입력창, 취소, 등록 버튼
- 즐겨찾기
- 닉네임, 폴더명 출력
- 폴더명 수정, 폴더 생성, 삭제 버튼
- 이전 페이지로 이동 버튼
- 폴더 내부 화장실 목록 출력, 스크롤
- 스크롤 적용
<br>
- 전체
- 스타일 수정
- 검색 결과
- 필터 목록 확인 및 수정
- 선택 상자 …

[FE] feat: 검색 결과, 리뷰 작성, 즐겨찾기 퍼블리싱

---

backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Toilet.java

---
title: "[BE] feat : 화장실 데이터 자료형 세부 수정"
---
<br>
- closes #38
<br>
<br>
- 화장실 데이터의 Boolean 타입을 MySQL의 TINYINT(1)로 변경했습니다.
- 화장실 데이터의 Decimal 타입의 범위를 수정했습니다.
<br>
-
-

#38 [BE-윤주] feat: 화장실 데이터 자료형 세부 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Toilet.java

---
title: "[BE] feat : d_female_poo 컬럼 삭제"
---
<br>
- closes #38
<br>
<br>
- 사용하지 않는 d_female_pee 컬럼을 삭제했습니다.
-
<br>
-
-

#38 [BE-윤주] feat: d_female_pee 컬럼 삭제

---

backend/build.gradle
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Role.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/SocialType.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/oauth/OAuthAttributes.java
backend/src/main/java/com/Fourilet/project/fourilet/oauth/userinfo/KakaoOAuth2UserInfo.java
backend/src/main/java/com/Fourilet/project/fourilet/oauth/userinfo/OAuth2UserInfo.java
backend/src/main/resources/application.yml

_---_
title: "[BE] feat: 소셜 로그인 구현 중 "
---
<br>
- closes #38
<br>
<br>
- 소셜 로그인을 구현하고 있습니다.
-
<br>
-
-

#38 [BE-윤주] feat: 소셜 로그인 구현 중

---

backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java

---
title: "[BE] fix: build 실패 수정"
---
<br>
- closes #38
<br>
<br>
- build 실패 원인을 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] fix: build 실패 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java

---
title: [BE-장엽] chore : 에러 해결
---
<br>
- #38 
<br>
<br>
- FolderDto 에러 해결
-
<br>
-
-

[BE-장엽] chore : 에러 해결

---

backend/src/main/java/com/Fourilet/project/fourilet/SecurityConfig.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
backend/src/main/resources/application.yml

---
title: "[BE] feat: Security Config 추가"
---
```
```
<br>
- closes (이슈 번호)
<br>
<br>
-
-
<br>
-
-

[BE] feat: Security Config 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java

---
title: "[BE] feat: Member Entity 사용하지 않는 컬럼 제거"
---
<br>
- closes #38
<br>
<br>
- Member Entity의 사용하지 않는 컬럼을 제거했습니다.
-
<br>
-
-

#38 [BE-윤주] feat: Member Entity 사용하지 않는 컬럼 제거

---

backend/build.gradle
backend/src/main/java/com/Fourilet/project/fourilet/config/SwaggerConfig.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/OAuthController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
backend/src/main/resources/application.yml

---
title: "[BE] feat: Swagger 연동"
---
<br>
- closes #38
<br>
<br>
- Swagger를 연동했습니다.
- Member API를 개발했습니다.
<br>
-
-

[BE] feat: Swagger 연동

---

frontend/android/app/src/main/AndroidManifest.xml
frontend/lib/main.dart
frontend/lib/screens/intro_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/select_theme_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_func.dart
frontend/lib/utilities/icon_image.dart
frontend/lib/utilities/settings_utils.dart
frontend/lib/utilities/style.dart
frontend/lib/utilities/type_enum.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/button.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/scroll_view.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/select_box.dart
frontend/lib/widgets/text_widget.dart
frontend/macos/Flutter/GeneratedPluginRegistrant.swift
frontend/pubspec.lock
frontend/pubspec.yaml

---
---
```
```
<br>
- closes #12 #45 #56 
<br>
<br>
- 확대/축소 버튼 표시, 표시 안 함 옵션 출력
- 글자 크기 기본, 큰 글씨 출력
- 지도 반경 300, 500, 700 m 출력
- 문의하기 터치 시, 메일 앱으로 이동
- 처리 방침 터치 시 방침 모달 나타남
- 라이선스 터치 시, 라이선스 모달 나타남
- 도움말 터치 시, 도움말 모달 나타남
<br>
- 설정 내용대로 앱에 적용하는 기능 미완료
- 문의하기 메일 내용에 기기 정보 추가
- 처리 방침, 라이선스, 도움말 내용 추가
- 로그인/로그아웃 기능 미구현

[FE] feat: 설정 화면 구현

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/BookMark.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Folder.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/BookMarkRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/BookMarkService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title : [BE] feat : folder 삭제 api
---
- #38 
<br>
<br>
- 유저의 폴더 삭제 api 개발
- 
<br>
- null  예외처리 해야함
-

[BE-장엽] feat : folder 삭제 api

---

frontend/lib/main.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/utilities/global_func.dart
frontend/lib/utilities/style.dart
frontend/lib/utilities/type_enum.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/button.dart
frontend/lib/widgets/scroll_view.dart
frontend/lib/widgets/select_box.dart

```
```
<br>
- closes #56 #59 
<br>
<br>
- 화장실 목록 터치 시, 리뷰 목록 출력
- 즐겨찾기, 메인 화면에서 화장실 목록 터치 시, 메인에서 화장실 목록과 리뷰 목록 출력
- 검색 화면에서 화장실 목록 터치 시, 검색 화면에서 화장실 목록과 리뷰 목록 출력 
- 검색 시 뜨는 정렬 선택 상자 제작
<br>
- 스타일 수정

[FE] feat: 리뷰 목록 출력, 선택 상자 기능 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/BookMark.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Folder.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Toilet.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/BookMarkRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/FolderRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: [BE-장엽] feat : folderAPI(폴더생성, 화장실 추가, 삭제 기능)
- #38 
<br>
<br>
- 화장실 즐겨찾기 폴더 생성 기능 구현
- 폴더에 화장실 추가, 삭제 기능 구현
<br>
- 
-

[BE-장엽] feat : folderAPI(폴더생성, 화장실 추가, 삭제 기능)

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ToiletController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/BookMark.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Folder.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Review.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Toilet.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/LoginDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/UpdateNicknameDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] feat: 화장실 API 개발"
---
<br>
- closes #38
<br>
<br>
- 화장실 API 개발 완료
- 
<br>
-
-

[BE] feat: 화장실 API 개발

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Review.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Toilet.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/Message.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/StatusEnum.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: feat: API 완료(예외처리필요)
---
- #38 
<br>
<br>
- API 작업완료
- 예외처리가 필요함. 이것은 따로 찾고있는중 
<br>
- X
-

[BE-장엽] feat: API 완료(예외처리필요)

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java

---
title: feat : 스웨거 추가
---
- #38  (이슈 번호)
<br>
<br>
- 스웨거 설명 추가
<br>

[BE-장엽] feat : 스웨거 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Folder.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: "[BE] : API  예외처리 "
---
- #38  (이슈 번호)
<br>
<br>
- 즐겨찾기 관련 예외처리 추가
- 
<br>
- 
-

[BE-장엽] feat : 예외처리 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: [BE] : 예외처리 
---
<br>
- #38 
<br>
<br>
- 즐겨찾기 관련 api 예외처리 완료
-
<br>

[BE-장엽] feat : 즐겨찾기 api 예외처리 완료

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: [Be] feat : 화장실별 리뷰 평균점수 제공, 화장실 추가 시 중복 검사 추가
---
- #38
<br>
<br>
- 화장실 별 리뷰 평균 점수 제공
- 즐겨찾기 폴더에 화장실 추가 시, 중복 검사 
<br>
- 
-

[BE - 장엽] feat : 화장실별 리뷰 평균점수 제공, 화장실 추가 시 중복 검사 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/config/SecurityConfig.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/service/JwtService.java
backend/src/main/java/com/Fourilet/project/fourilet/config/oauth2/handler/OAuth2LoginSuccessHandler.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
backend/src/main/resources/application.yml

---
title: "[BE] feat: token 유효시간 수정 "
---
<br>
- closes #38
<br>
<br>
- token 유효시간 수정
-
<br>
-
-

#38 [BE-윤주] feat: token 유효시간 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/OAuthController.java
backend/src/main/resources/application.yml

---
title: "[BE] feat: kakao accesstoken 확인"
---
<br>
- closes #38
<br>
<br>
-
-
<br>
-
-

#38 [BE-윤주] feat: kakao accesstoken 확인

---

backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java

---
title: [BE] feat : 중복삭제 예외처리, 리뷰의 갯수 추가
---
- #38 
<br>
<br>
- 리뷰 갯수 추가
- 화장실 중복 삭제 예외 처리 
<br>
-
-

[BE-장엽] feat : 중복삭제 예외처리, 리뷰의 갯수 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/exception/LimitException.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java

---
title: [BE] refactor : 예외처리 수정
<br>
- #38 
<br>
<br>
- 즐겨찾기 폴더 이름 업데이트 api 수정
- 한 유저 당 10개 이상의 즐겨찾기 생성 제한
- 로그인 때마다 기본 즐겨찾기가 생성 된 것을 회원가입 시에만 생성되는 것으로 수정
- 커스텀 Exception 추가
<br>
-
-

[BE] refactor : 예외처리 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: [BE] : review 등록 예외처리
---
<br>
- #38 
<br>
<br>
- 예외처리 함
-
<br>
-
-

[BE-장엽] feat : review 등록 부분 예외처리

---

backend/src/main/java/com/Fourilet/project/fourilet/config/CustomAuthenticationEntryPoint.java
backend/src/main/java/com/Fourilet/project/fourilet/config/SecurityConfig.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/service/JwtService.java
backend/src/main/resources/application.yml

---
title: "[BE] feat: token 만료 시 상태 코드 401로 수정"
---
<br>
- closes #38
<br>
<br>
- token 만료 시의 에러 코드를 403에서 401로 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] feat: token 만료 시 상태 코드 401로 수정

---

backend/build.gradle
backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryCustom.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java

---
title: "[BE] fix: docker build 실패 확인"
---
<br>
- closes #38
<br>
<br>
- Docker 빌드 실패 확인, 원인 파악 중
-
<br>
-
-

#38 [BE-윤주] fix: docker build 실패 확인

---

backend/src/main/generated/com/Fourilet/project/fourilet/data/entity/QBookMark.java
backend/src/main/generated/com/Fourilet/project/fourilet/data/entity/QFolder.java
backend/src/main/generated/com/Fourilet/project/fourilet/data/entity/QMember.java
backend/src/main/generated/com/Fourilet/project/fourilet/data/entity/QReview.java
backend/src/main/generated/com/Fourilet/project/fourilet/data/entity/QToilet.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/service/JwtService.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/util/PasswordUtil.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] fix: 사용하지 않는 로그 정리"
---
<br>
- closes #38
<br>
<br>
- ec2 용량 확보를 위해 사용하지 않는 로그를 정리했습니다.
-
<br>
-
-

#38 [BE-윤주] fix: 사용하지 않는 로그 정리

---

backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Member.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/MemberRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java

---
title: "[BE] chore : Member API 요구사항 반영"
---
<br>
- closes #38
<br>
<br>
- 로그인 / 회원가입 여부 추가
- 닉네임 중복 방지 추가
<br>
-
-

#38 [BE-윤주] chore : Member API 요구사항 반영

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/PageDto.java

---
title: "[BE] feat :  accessToken으로 member 식별 코드 작성 
- #38 
<br>
<br>
- 토큰 확인
-
<br>
-
-

[BE-장엽] feat : accessToken으로 member 식별 코드 작성

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: "[BE] feat : 즐겨찾기 명 10자이내로 제한"
---
- #38 
<br>
<br>
- 즐겨찾기 폴더 명 10자이내로 제한
-
<br>
-
-

[BE-장엽] feat: 즐겨찾기 명 10자이내로 제한

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/MemberController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java

---
title: "[BE] chore: 닉네임 수정 10자 제한"
---
<br>
- closes #38 
<br>
<br>
- 닉네임 수정 api의 10자 제한을 추가했습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 닉네임 수정 10자 제한

---

frontend/.gitignore
frontend/lib/main.dart
frontend/lib/providers/api_provider.dart
frontend/lib/providers/bookmark_provider.dart
frontend/lib/providers/review_provider.dart
frontend/lib/providers/state_provider.dart
frontend/lib/providers/user_provider.dart
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/intro_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/select_theme_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/utilities/icon_image.dart
frontend/lib/utilities/settings_utils.dart
frontend/lib/utilities/type_enum.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/modal.dart
frontend/pubspec.lock
frontend/pubspec.yaml

---
---
```
```
<br>
- closes #91 
- closes #95 
- closes #74
<br>
<br>
- 로그인
- access token, refresh token, nickname 데이터 조회, 변경 삭제 기능 구현 (상태 관리)
- 로그인 데이터 변경 시 화면 변경 구현
- 토큰 유효 기간 만료 시 token 재발급
- 모든 api 요청마다 적용
- token 재발급 후 요청 다시 전송  
- 자동 로그인
- 앱 접속 시, access token 여부에 따른 자동 로그인 시도
- 오류 발생 시 정보 초기화
- 화면 새로 고침
- 즐겨찾기 폴더 생성/삭제 시 화면 새로 고침 
<br>
- 토큰 유효 기간 만료 시 token 재발급 부분 테스트 필요

[FE] feat: 로그인 데이터 상태 관리 및 자동 로그인, 화면 새로고침

---

backend/src/main/java/com/Fourilet/project/fourilet/config/SecurityConfig.java

---
title: "[BE] chore: security review 조회 권한 수정"
---
<br>
- closes #38
<br>
<br>
- 로그인을 하지 않아도 화장실의 리뷰를 조회할 수 있도록 spring security 권한을 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] chore: security review 조회 권한 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] chore: 화장실 API 북마크 여부 데이터 반환 수정"
---
<br>
- closes #38
<br>
<br>
- 화장실 API의 북마크 여부를 기존의 true/false에서 해당 화장실을 해당 유저가 북마크한 폴더id를 반환하도록 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 화장실 API 북마크 여부 데이터 반환 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: "[BE] chore: 즐겨찾기 폴더 내 화장실 목록의 북마크 여부를 forderId로 수정"
---
<br>
- closes #38
<br>
<br>
- 즐겨찾기 폴더 내 화장실 목록의 북마크 여부를 기존의 true/false에서 소속된 forderId가 반환되도록 수정하였습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 즐겨찾기 폴더 내 화장실 목록의 북마크 여부를 forderId로 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: 리뷰 여부 확인 코드 추가
---
<br>
- #38 
<br>
<br>
- 즐겨찾기 폴더 내의 리뷰 여부 확인 코드 추가
<br>

#38 [BE-장엽] chore : 리뷰 여부 확인 코드 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] chore: 화장실 API 리뷰 작성 여부 확인 추가"
---
<br>
- closes #38
<br>
<br>
- 화장실 API에 리뷰 작성 여부를 확인하여 작성했을 경우 ReviewId를 반환하도록 추가하였습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 화장실 API 리뷰 작성 여부 확인 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/StatusEnum.java

---
title: "리뷰목록 조회 상태코드 변경 "
---
<br>
- #38 
<br>
<br>
- 리뷰가 없을때 상태코드 변경
-
<br>

#38 [BE-장엽] chore : 리뷰목록 조회 상태코드 변경

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: 개별리뷰조회 api추가
---
<br>
- #38 
<br>
<br>
- 개별 리뷰 목록 조회 api 추가
<br>

#38 [BE-장엽] feat: 개별리뷰조회 api추가

---

frontend/.gitignore
frontend/lib/main.dart
frontend/lib/models/review_model.dart
frontend/lib/models/toilet_model.dart
frontend/lib/providers/api_provider.dart
frontend/lib/providers/bookmark_provider.dart
frontend/lib/providers/review_provider.dart
frontend/lib/providers/state_provider.dart
frontend/lib/providers/toilet_provider.dart
frontend/lib/providers/user_provider.dart
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/intro_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/screens/select_theme_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/utilities/settings_utils.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/list_view.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/scroll_view.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart
frontend/pubspec.lock

---
---
```
```
<br>
- closes #74 
- closes #114
- closes #69 
<br>
<br>
- 즐겨찾기 폴더 내 화장실 목록
- 높이, 너비, 내부 위젯 크기 조정
- 리뷰를 작성한 적이 있는 화장실에서는 리뷰 작성 버튼이 리뷰 수정 버튼으로 변경됨
- 외부 내비게이션 앱으로 이동
- 리뷰 조회
- 개별 화장실 터치 시, 리뷰 목록 조회
- 상단에 화장실 정보 출력
- 리뷰 수정
- 생성과 분기 처리
- 개별 리뷰 정보 받아와 출력
- 즐겨찾기 폴더 목록
- 폴더 내부 디자인 수정
- 폴더 생성/삭제, 폴더명 수정 시, 새로고침 적용
- 테마 선택 화면
- 디자인 수정
- 리뷰 삭제 
- 즐겨찾기 삭제
- 즐겨찾기 폴더 내 즐겨찾기 삭제
- 뒤로 가기 버튼 두 번 눌렀을 경우 앱 종료
- 상태 반영 안 되는 오류 수정  
<br>
- 추후 할 …

[FE] feat: 화장실 목록 및 리뷰 조회, 외부 내비게이션 앱 연결, 리뷰 수정, 리뷰 및 즐겨찾기 삭제

---

README.md

---
title: "[BE] chore : 화장실 API null 오류 수정"
---
<br>
- closes #38
<br>
<br>
-
-
<br>
-
-

#38 [BE-윤주] chore : 화장실 API null 오류 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

Revert "[BE-장엽] chore: review 최신순 정렬"

---

backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: chore: review 최신순 정렬
---
- #38 
<br>
<br>
- review 최신순 반환 수정
-
<br>
-
-

[BE-장엽] chore: review 최신순 정렬

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: [BE] 전체리뷰 사이즈 반환 수정
---
<br>
- #38 
<br>
<br>
- 해당 화장실의 전체 리뷰 목록의 길이 반환 수정
<br>

[BE-장엽] chore : 전체리뷰 사이즈 반환 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/dto/ReviewDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: 전체리뷰 사이즈 반환 수정
---
<br>
- #38
<br>
<br>
- 전체 페이지 수 반환
<br>

[BE-장엽] chore : 전체 페이지 수 반환 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/Message2.java

---
title: chore: message 2 추가
---
- #38 
<br>
<br>
- 리뷰리스트 사이즈 제공을 위한 message2 클래스 추가

[BE-장엽] chore: message 2 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/BookMarkRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ToiletRepositoryImpl.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] chore: 북마크 여부 폴더 id 리스트로 변경"
---
<br>
- closes #38
<br>
<br>
- 북마크 여부를 판별하는 FolderId를 기존의 Long에서 List<Long>으로 변경하여 여러 폴더에서 북마크하고 있는 경우를 처리해주었습니다.
<br>
-
-

#38 [BE-윤주] chore: 북마크 여부 폴더 id 리스트로 변경

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/BookMarkRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/Message.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto2.java
backend/src/main/java/com/Fourilet/project/fourilet/exception/AtLeastException.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: [BE] 즐겨찾기 폴더 삭제 제한 추가, 폴더 내의 화장실 목록에 페이지네이션 적용
---
- #38 
<br>
<br>
- 즐겨찾기 폴더 삭제 제한 추가(폴더는 적어도 1개 이상이 존재해야함)
- 폴더 내의 화장실 목록에 페이지네이션 적용
<br>
-
-

[BE-장엽] chore : 즐겨찾기 폴더 삭제 제한 추가, 폴더 내의 화장실 목록에 페이지네이션 적용

---

backend/build.gradle
backend/src/main/java/com/Fourilet/project/fourilet/config/CustomPageable.java
backend/src/main/java/com/Fourilet/project/fourilet/config/SwaggerConfig.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ToiletController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] chore: 불필요한 pageable 관련 정보를 삭제 및 Swagger의 설정 수정"
---
```
<br>
- closes #38
<br>
<br>
- 불필요한 Pageable 관련 정보를 삭제했습니다.
- Swagger의 Pageable 설정을 커스텀하여 사용하기 쉽게 수정하였습니다.
<br>
-
-

#38 [BE-윤주] chore: 불필요한 pageable 관련 정보를 삭제 및 Swagger의 설정 수정

---

backend/src/main/resources/application.yml

---
title: "[BE] chore : API Token FE 테스트를 위해 유효기간 변경"
---
<br>
- closes #38
<br>
<br>
- 프론트엔드 API Toekn 테스트를 위해 유효기간을 잠시 변경합니다. (액세스 5분, 리프레시 10분)
-
<br>
-
-

#38 [BE-윤주] chore : API Token FE 테스트를 위해 유효기간 변경

---

backend/src/main/resources/application.yml

---
title: 토큰테스트를 위한 유효기간 변경
---
<br>
- #38 
<br>
<br>
- 엑세스, 리프레시 토큰 유효기간 변경

[BE-장엽] chore : 토큰테스트를 위한 유효기간 변경

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/resources/application.yml

---
title: [BE] 폴더에 화장실추가 삭제 api 통합
---
<br>
- #38  
<br>
<br>
- 특정 폴더 내에 화장실 추가 삭제 통합
- 매개변수를 리스트로 받아 한번에 삭제, 추가 가능
<br>
-
-

[BE-장엽] chore : 폴더에 화장실추가 삭제 api 통합

---

backend/src/main/java/com/Fourilet/project/fourilet/config/SwaggerConfig.java
backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ToiletController.java
backend/src/main/resources/application.yml

---
title: "[BE] chore: token 만료 시 응답값 변경 테스트 "
---
<br>
- closes #38
<br>
<br>
- token 만료 혹은 유효하지 않은 토큰일 경우 응답값을 변경하는 테스트 중입니다.
-
<br>
-
-

#38 [BE-윤주] chore: token 만료 시 응답값 변경 테스트

---

backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/resources/application.yml

---
title: "[BE] chore: 토큰 만료 시 access와 refresh 구분 테스트"
---
<br>
- closes #38
<br>
<br>
- 토큰 만료 시 access와 refresh를 구분하기 위해 테스트합니다
-
<br>
-
-

#38 [BE-윤주] chore: 토큰 만료 시 access와 refresh 구분 테스트

---

backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java
backend/src/main/resources/application.yml

---
title: "[BE] chore: 리프레시&액세스 토큰 만료 및 유효성 구분"
---
<br>
- closes #38
<br>
<br>
- 토큰 만료 및 유효하지 않은 토큰일 경우, 액세스와 리프레시가 다른 메시지를 반환하도록 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 리프레시&액세스 토큰 만료 및 유효성 구분

---

backend/src/main/java/com/Fourilet/project/fourilet/config/jwt/filter/JwtAuthenticationProcessingFilter.java

---
title: "[BE] chore : 화장실 리뷰 조회 토큰 검사 로직 수정"
---
<br>
- closes #38
<br>
<br>
- 토큰이 없어도 (로그인하지 않아도) 화장실의 리뷰를 조회할 수 있도록 토큰 검사 로직을 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 화장실 리뷰 조회 토큰 검사 로직 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/resources/application.yml

---
title: 다중 폴더에 화장실 추가 삭제로 수정
---
- #38 
<br>
<br>
- 다중폴더 선택한 후 화장실 추가 삭제
- 엑세스토큰, 리프레쉬 토큰 만료시간 수정
<br>
-
-

[BE-장엽] chore : 다중 폴더에 화장실 추가 삭제로 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: "[BE] chore : score 소수점 둘째 자리까지 표시"
---
- #38
<br>
<br>
- 평점 소수점 둘째자리까지 표시 수정

[BE-장엽] chore : score 소수점 둘째 자리까지 표시

---

backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] chore: 평점 평균 소수 자릿수 수정"
---
<br>
- closes #38
<br>
<br>
- 평점 평균의 소수 자릿수를 2자리로 수정했습니다.
-
<br>
-
-

#38 [BE-윤주] chore: 평점 평균 소수 자릿수 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/data/repository/ReviewRepository.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: "[BE] chore : 리뷰어가 같은 화장실에 또 리뷰를 쓰지 않도록 함"
---
<br>
- #38 
<br>
<br>
- 같은 멤버가 또 다른 리뷰를 작성하지 않도록 함
-
<br>

[BE-장엽] chore : 리뷰어가 같은 화장실에 또 리뷰를 쓰지 않도록 함

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/FolderDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java

---
title: 즐겨찾기에 화장실 추가 삭제 api 수정
---
<br>
- #38 
<br>
<br>
- 즐겨찾기에 화장실 추가 삭제 api 수정

[BE-장엽] chore : 즐겨찾기에 화장실 추가 삭제 api 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java

---
title: [BE] api url 변경
<br>
- #38 
<br>
<br>
- url 변경

[BE-장엽] chore: api url 변경

---

frontend/lib/providers/state_provider.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/utilities/icon_image.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/button.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart
frontend/lib/widgets/text_widget.dart

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 충돌 오류 수정
- 디자인 수정
<br>
-
-

[FE] chore: 오류/디자인 수정 

---

frontend/lib/widgets/modal.dart

---
---
```
```
<br>
- closes #136
<br>
<br>
- 로그인 테스트 코드 추가
<br>
-
-

[FE] test: 로그인 테스트 코드 추가

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/ToiletController.java
backend/src/main/java/com/Fourilet/project/fourilet/dto/ToiletDto.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] feat : 특정 화장실 정보 조회 API 추가 개발"
---
<br>
- closes #38 
<br>
<br>
- 프론트팀 요청으로 특정 화장실의 정보를 조회하는 API를 개발했습니다.
- 유효하지 않은 화장실 id로 요청 시 Bad Request를 반환하게 오류 처리했습니다.
<br>
-
-

#38 [BE-윤주] feat: 특정 화장실 정보 조회 API 추가 개발

---

frontend/lib/screens/main_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/widgets/search_bar.dart

---
---
```
```
<br>
- closes #136
<br>
<br>
- search bar를 custom search bar로 이름 변경
-
<br>
-
-

#136 [FE-원경] chore: search bar 이름 변경

---

backend/src/main/resources/application.yml

---
title: "[BE] chore: 토큰 테스트를 위해 유효시간 변경"
---
<br>
- closes #38
<br>
<br>
- 프론트와 토큰 갱신 테스트를 위해 액세스, 리프레시 유효시간 변경
-
<br>
-
-

#38 [BE-윤주] chore: 토큰 테스트를 위해 유효시간 변경

---

backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: "BE] chore: review 등록 오류 수정 
---
<br>
- #38 
- 
<br>
<br>
- review가 16개 등록되는 것을 수정

[BE-장엽] chore: review 등록 오류 수정

---

frontend/lib/main.dart
frontend/lib/providers/state_provider.dart
frontend/lib/providers/user_provider.dart
frontend/lib/screens/book_mark_folder_screen.dart
frontend/lib/screens/intro_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/utilities/style.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/button.dart
frontend/lib/widgets/icon.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart
frontend/lib/widgets/text_widget.dart

---
---
```
```
<br>
- closes (이슈 번호)
<br>
<br>
- QA 수정 사항 반영
- 글자 크기 반영
- 리뷰 등록 오류 수정
- 검색 정렬 기능 반영
- 디자인 수정
- 글자 크기 기기 설정과 독립시킴
- 글자 크기 조정
- 화장실 정보 순서 변경
- padding, 위치 조절
<br>
-
-

[FE] chore: 오류/디자인 수정

---

frontend/lib/main.dart
frontend/lib/providers/api_provider.dart
frontend/lib/providers/bookmark_provider.dart
frontend/lib/providers/review_provider.dart
frontend/lib/providers/state_provider.dart
frontend/lib/providers/toilet_provider.dart
frontend/lib/screens/book_mark_folder_screen.dart
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/utilities/style.dart
frontend/lib/utilities/type_enum.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/map_widget.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart
frontend/lib/widgets/text_widget.dart

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 무한 스크롤 관련 데이터 전역 변수화
- 코드 리팩토링
- 작업 후 데이터 갱신
<br>
- 데이터 갱신 부분 작업 중

[FE] chore: 무한 스크롤, 데이터 갱신

---

frontend/lib/providers/state_provider.dart
frontend/lib/providers/toilet_provider.dart
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/intro_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/button.dart
frontend/lib/widgets/map_widget.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 메인 화면 데이터 갱신
- 무한 스크롤
- 로그인 모달 오류 수정
- UI/UX 수정
<br>
- 데이터 갱신 미완료

[원경] chore: 데이터 갱신 및 무한스크롤 오류 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java

---
title: [BE] chore : review 등록 오류 수정
- #38 
<br>
<br>
- 리뷰 등록 수정 오류
-
<br>
-
-

[BE-장엽] chore : review 등록 오류 수정

---

frontend/lib/providers/state_provider.dart
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart
frontend/lib/widgets/text_widget.dart

---
---
```
```
<br>
- closes (이슈 번호)
<br>
<br>
- 무한 스크롤 점검 및 오류 수정
- 데이터 갱신 점검 및 오류 수정
- 기타 오류 수정
- 디자인 수정

[FE] chore: 무한 스크롤, 데이터 갱신 및 기타 오류/디자인 수정

---

frontend/lib/screens/main_screen.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/map_widget.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/text_widget.dart

---
---
```
```
<br>
- closes #136 
<br>
<br>
- input 모달 디자인 수정
- x 버튼 존재하는 모달 디자인 수정
- 기본 모달 디자인 수정

[FE] chore: 모달 디자인 수정

---

frontend/lib/providers/state_provider.dart
frontend/lib/providers/toilet_provider.dart
frontend/lib/providers/user_provider.dart
frontend/lib/screens/book_mark_screen.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/review_form_screen.dart
frontend/lib/screens/search_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/lib/widgets/silvers.dart

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 화장실 목록 높이 조회 오류
- 리뷰 모드에서 화장실 정보 출력 부분 높이 조절
- 리뷰 모드에서 화장실 목록 미갱신 오류 수정
- UI/UX 수정

[FE] chore: 화장실 목록 높이 조회 오류 수정 및 화장실 목록 미갱신 오류 수정

---

frontend/lib/screens/main_screen.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/map_widget.dart

---
---
```
```
<br>
- closes #70 
<br>
<br>
- 지도 초기 마커 갱신
- 마커 터치 시 화장실 목록 출력

[FE] feat: 지도 초기 마커 갱신 및 마커 터치 시 화장실 목록 출력

---

frontend/android/app/build.gradle
frontend/android/app/proguard-rules.pro
frontend/android/app/src/main/AndroidManifest.xml
frontend/lib/widgets/box_container.dart

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 코드 난독화 및 경량화
- 불필요한 위젯 제거

[FE] feat: release 설정 및 회색 화면 오류 수정

---

frontend/android/build.gradle
frontend/lib/providers/state_provider.dart
frontend/lib/providers/user_provider.dart
frontend/lib/screens/main_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/utilities/global_utils.dart
frontend/lib/utilities/oss_licenses.dart
frontend/lib/utilities/settings_utils.dart
frontend/lib/widgets/bottom_sheet.dart
frontend/lib/widgets/box_container.dart
frontend/lib/widgets/modal.dart
frontend/pubspec.yaml

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 서비스 탈퇴 기능 추가
- 마커 미변경 오류 수정

[FE] feat: 서비스 탈퇴 기능 추가 및 마커 미변경 오류 수정

---

frontend/lib/screens/intro_screen.dart
frontend/lib/screens/settings_screen.dart
frontend/lib/widgets/modal.dart
frontend/lib/widgets/search_bar.dart
frontend/pubspec.yaml

---
---
```
```
<br>
- closes #136 
<br>
<br>
- 이미지 화질 조정
- 검색 필터 문구 수정 (overflow 오류 수정)

[FE] fix: 이미지 화질 조정 및 overflow 오류 수정

---

backend/src/main/java/com/Fourilet/project/fourilet/controller/FolderController.java
backend/src/main/java/com/Fourilet/project/fourilet/controller/ReviewController.java
backend/src/main/java/com/Fourilet/project/fourilet/service/FolderService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ReviewService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: [BE] fix : 사용하지 않는 로그, 주석 삭제
<br>
-  #38 
<br>
<br>
- 사용하지 않는 로그, print문 삭제
<br>
-
-

[BE-장엽] fix : 사용하지 않는 로그, 주석 삭제

---

backend/src/main/java/com/Fourilet/project/fourilet/data/entity/Toilet.java
backend/src/main/java/com/Fourilet/project/fourilet/service/MemberService.java
backend/src/main/java/com/Fourilet/project/fourilet/service/ToiletService.java

---
title: "[BE] chore: Print문과 쓸모없는 주석 정리"
---
<br>
- closes (이슈 번호)
<br>
<br>
- print문을 삭제했습니다.
- 사용하지 않는 변수나 함수를 주석처리한 부분을 삭제했습니다.
<br>
-
-

#38 [BE-윤주] chore: Print문과 쓸모없는 주석 정리

---

frontend/lib/screens/main_screen.dart
frontend/lib/utilities/settings_utils.dart
frontend/lib/widgets/bottom_sheet.dart

---
---
```
```
<br>
- closes #190 
<br>
<br>
- 필터 뜨지 않는 오류 수정
- 백엔드 라이선스 추가

[FE] chore: 필터 뜨지 않는 오류 수정 및 백엔드 라이선스 추가
